[package]
name = "diwan_core"
description.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
readme.workspace = true
repository.workspace = true

[dependencies]
anyhow = "1.0.86"
crossterm = "0.27.0"
